README.md

@sidwray, I fixed the link to the samples in the readme, but it won't work until dev is merged into master.

readme - fixing links

---

index.html

removed image link, but not image.

Fix-reference-box

---

docs/api-reference.md

Removing "plugin" term from content. Added links to resolvers example.

update api-reference.md to remove plugins

---

_config.yml

Removing "plugin" from title and description.

Change title and description in config.yml

---

_includes/header.html

Removed 'plugin' references. Added links in the top nav to docs, api reference, capabilities.

Updated header.html

---

docs/capabilities.md

Added a key for the table. Removed all old version information.

Edit Capabilities

---

_includes/docs_menu.html
docs/design.md
docs/dialect.md

Added new dialect (TDD) topic. Updated TOC and Design with new topic.

---

docs/share.md

Clarifying based on partner feedback

Update Tableau Server config steps

---

docs/api-reference.md

update formatKeyValuePair, log, locateDriver function names

update formatKeyValuePair, log, locateDriver function names

---

docs/api-reference.md

Update documentation for new javascript helper methods in 2019.2. Does not include company and support link documentation, still working on those.

Update API changes for 2019.2

---

packaging/package/xsd_validator.py

* Fixed some flake8 nits (you can [have VS Code do it for you](https://code.visualstudio.com/docs/python/linting)).
* Added a [docstring](
https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings) that may not be 100% PEP-257 friendly because it used [this VS Code plugin](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring)

flake8 nits plus a docstring

---

packaging/package/jar_packager.py
packaging/package/manifest.py
packaging/package/package.py

Add jar package functionality, last PR was discarded.
manifest package refactored, add flexibility to define jar file destination dir.

Package jsun

---

packaging/package/jar_packager.py
packaging/package/package.py
packaging/setup.py

`six` is imported in `manifest.py`

add six to install_requires

---

packaging/package/jar_packager.py
packaging/package/package.py

1. update validate XML then create jar logic in package.py
2. change relative path, default jar file destination dir will be connector-plugin-sdk\packaging\jar

change validate xml then create jar logic, and change default jar file destination

---

packaging/package/package.py

Commands so far:
--package [folder_path] (package files at that folder path)
--validate [folder_path] (only validate the xml file at that location)
--verbose or -v (output more to the console)

Add command line arguments for folder path

---

packaging/package/connector_file.py
packaging/tests/test_connector_file.py

Use os.path.splitext to get ConnectorFile extension.

Use os.path.splitext to get ConnectorFile extension.

---

packaging/package/manifest.py

1. refactor manifest package about sections
2. add vendor section in generated manifest file, new section looks like:
Created-By: Tableau Connector SDK 0.0.1

refactor manifest and add vendor section

---

packaging/package/connector_file.py
packaging/tests/test_resources/broken_xml/connectionResolver.tdr
packaging/tests/test_resources/broken_xml/manifest.xml
packaging/tests/test_resources/wrong_class/connection-dialog.tcd
packaging/tests/test_resources/wrong_class/connectionBuilder.js
packaging/tests/test_resources/wrong_class/connectionResolver.tdr
packaging/tests/test_resources/wrong_class/dialect.tdd
packaging/tests/test_resources/wrong_class/manifest.xml
packaging/tests/test_xml_parser.py
packaging/tests/test_xsd_validator.py

Had to add some comparison stuff to connector file to compare file lists

Add unit tests for xml parser and xsd validator

---

packaging/package/package.py
packaging/tests/test_package.py
packaging/tests/test_xml_parser.py

Also a bit of formatting in test_xml_parser. For test_package, I just call it in the test and then check to see if the packaged connector is created where we expect. We test the individual bits well enough in the other suites I think, but I still want a review on this because it's kind of ugly.

Add packager unit tests

---

packaging/package/package.py
packaging/package/xml_parser.py
packaging/package/xsd_validator.py

Made some errors or failures print to the console so the person running it can see quickly what went wrong before going deep into the logs.

Log more errors to console

---

packaging/package/xml_parser.py

If we see a translatable string in the xml, we will add in all the resource files we can find and validates them.

Find and package resource files

---

tdvt/samples/config/tdvt/tdvt.ini
tdvt/tdvt/config_gen/test_config.py
tdvt/tdvt/tdvt.py
tdvt/test/tdvt_test.py

Test maintainence

---

samples/components/dialects/Hive12Dialect.tdd
samples/components/dialects/full_dialect.tdd

Fixed date-function mappings.

---

docs/api-reference.md
docs/example.md

A WIP PR to see the changes from `2019.2-docs-holding` that will go into `gh-pages-dev`.

Merge 2019.2-docs-holding into gh-pages-dev

---

docs/tdvt.md

[Docs] update sample ini to include [ConnectionTest]

---

packaging/README.md
packaging/package/package.py

- fix --validate_only to --validate-only
- add signing to readme

add signing changes to readme

---

packaging/README.md
samples/plugins/mysql_odbc/connectionBuilder.js
samples/plugins/mysql_odbc/connectionDialog.tcd
samples/plugins/mysql_odbc/connectionResolver.tdr
samples/plugins/mysql_odbc/manifest.xml
samples/plugins/postgres_jdbc/manifest.xml
samples/plugins/postgres_odbc/manifest.xml
validation/connector_plugin_manifest_latest.xsd

Update connector_plugin_manifest_latest.xsd 
Add min-version-tableau in sample plugins
Add vendor-information in manifest.xml for sample plugins

TFSID951139: [TDVT] Update sample plugins in SDK

---

validation/connector_plugin_manifest_latest.xsd

Update xsd to be same as monolith

Update dev branch's xsd to be same as monolith

---

tdvt/tdvt/tdvt.py

change references to tdvt_runner to py -3 -m tdvt.tdvt

---

.gitignore
_includes/docs_menu.html
docs/localize.md

Added a doc page for localization support.

document localization support

---

docs/auth-modes.md
docs/localize.md

Add localization document page, it has been reviewed once when before it merged to gh-pages-dev branch.

Add localization document page

---

docs/localize.md

add Spanish example

---

_includes/head.html

For TFS969929 fixes xss vulnerability

Bump css and js version of bootstrap to fix xss issue

---

samples/plugins/postgres_odbc/connectionBuilder.js

Add code snippet to use odbc-connect-string-extras set in postgres_odbc

Update postgres_odbc connectionBuilder.js

---

samples/plugins/mysql_odbc/connectionBuilder.js

Add code snippet to use odbc-connect-string-extras set in mysql_odbc

Update mysql_odbc connectionBuilder.js

---

samples/plugins/postgres_odbc/connectionBuilder.js

fix postgres odbc example

---

samples/plugins/postgres_jdbc/connectionBuilder.js
samples/plugins/postgres_jdbc/connectionProperties.js
samples/plugins/postgres_jdbc/connectionResolver.tdr

This is the same pattern used for MaxCompute. Tested in 2019.3.

Add properties builder to postgres_jdbc

---

_includes/docs_menu.html

Change menu title

---

samples/plugins/postgres_jdbc/connection-dialog.tcd
samples/plugins/postgres_jdbc/connectionProperties.js
samples/plugins/postgres_odbc/connectionBuilder.js

The ODBC sample had a checkbox that did nothing. Added the logic in the connection builder, and then added the checkbox and logic to the JDBC sample.

Fix ssl for postgres examples

---

tdvt/tdvt/tdvt.py

Same change as in #287, branched off `dev-tdvt` and with updated wording.

Fix smoke tests

---

samples/components/dialogs/new_text_field/connection-dialog.tcd
samples/components/dialogs/new_text_field/connectionBuilder.js
samples/components/dialogs/new_text_field/connectionRequired.js
samples/components/dialogs/new_text_field/connectionResolver.tdr

Add vendor attributes to the text field components sample.

Added service to the required attribute list

---

samples/plugins/postgres_jdbc/connection-dialog.tcd
samples/plugins/postgres_jdbc/connectionProperties.js
samples/plugins/postgres_jdbc/connectionResolver.tdr

Update the postgres_jdbc sample to have vendor attributes

Vendor attributes

---

README.md

Updating since the packager requires 3.7

Update readme python version

---

docs/ui.md

Reverts tableau/connector-plugin-sdk#322

Revert "Vendor attributes documentation "

---

samples/components/dialogs/new_text_field/connection-dialog.tcd
samples/components/dialogs/new_text_field/connectionBuilder.js
samples/components/dialogs/new_text_field/connectionRequired.js
samples/components/dialogs/new_text_field/connectionResolver.tdr

Reverts tableau/connector-plugin-sdk#301
Reverting so dev is mergable to master.
Can cherry pick the reverted commits into vNext/tdvt-dev as appropriate

Revert "Added service to the required attribute list"

---

samples/plugins/postgres_jdbc/connection-dialog.tcd
samples/plugins/postgres_jdbc/connectionProperties.js
samples/plugins/postgres_jdbc/connectionResolver.tdr

Reverts tableau/connector-plugin-sdk#304
Reverting to dev is mergable to master. We can cherry pick these into `tdvt-dev` or `vNext` as appropriate.

Revert "Vendor attributes"

---

CHANGELOG.md
samples/plugins/sqlite_extract/connectionBuilder.js
samples/plugins/sqlite_extract/connectionDialog.xml
samples/plugins/sqlite_extract/connectionResolver.xml
samples/plugins/sqlite_extract/dialect.xml
samples/plugins/sqlite_extract/manifest.xml

Adds extract-only SQLite connector to show how to make an extract-only connector. Uses ODBC driver.

Add sample extract-only connector

---

docs/api-reference.md
docs/package-sign.md

Testing to see if formatting fixes stick.

Gh pages dev

---

_includes/docs_menu.html
docs/api-reference.md
docs/example.md
docs/index.md
docs/package-sign.md
docs/run-taco.md
docs/share.md
docs/ui.md

Right now, this vnext branch does not have the latest dev changes.

Merge gh-pages-dev into gh-pages-dev-2020.1

---

tdvt/CHANGELOG.md
tdvt/tdvt/tdvt.py

Makes the following changes:
* A Path object is created with `args.run_file`
* TDVT checks if the file exists before continuing.
* `output_dir` is also a Path object
* the `run_file()` fn is updated to work with Path objects.
* `enqueue_failed_tests()` is updated to work with Path objects.

Update run_file to check if file exists

---

samples/components/resolvers/connectionBuilder.js
samples/plugins/mysql_odbc/connectionBuilder.js
samples/plugins/postgres_odbc/connectionBuilder.js

Reverting some merges into dev that should be in vNext.

Revert merges that should be in vNext

---

samples/plugins/postgres_jdbc/connection-dialog.tcd
samples/plugins/postgres_jdbc/connectionProperties.js
samples/plugins/postgres_jdbc/connectionResolver.tdr

Bring back @saugatt's `vendorAttributes` changes.

Update postgres_jdbc with optional fields

---

connector-packager/tests/test_resources/valid_connector/manifest.xml

Adds vendor info to the valid connector in the test resources folder so it is valid.

Fix packager tests

---

.github/pull_request_template.md
CHANGELOG.md
README.md
connector-packager/CHANGELOG.md
connector-packager/connector_packager/helper.py
samples/components/dialects/full_dialect.tdd
samples/plugins/mysql_odbc/connectionBuilder.js
samples/plugins/mysql_odbc/connectionResolver.tdr
samples/plugins/mysql_odbc/manifest.xml
samples/plugins/postgres_jdbc/connectionResolver.tdr
samples/plugins/postgres_jdbc/manifest.xml
samples/plugins/postgres_odbc/connectionBuilder.js
samples/plugins/postgres_odbc/connectionResolver.tdr
samples/plugins/postgres_odbc/manifest.xml
samples/plugins/sqlite_extract/connectionBuilder.js
samples/plugins/sqlite_extract/connectionDialog.xml
samples/plugins/sqlite_extract/connectionResolver.xml
samples/plugins/sqlite_extract/dialect.xml
samples/plugins/sqlite_extract/manifest.xml
tdvt/CHANGELOG.md
tdvt/tdvt/tdvt.py
validation/connector_plugin_manifest_latest.xsd

Bring `master` into `dev-tdvt` so we have the latest hotfixes, etc.
After this gets merged I'm going to merge #378 with changelog updates into `tdvt-dev` and then merge into `master` so we can do a release.

Master to dev tdvt

---

CHANGELOG.md
validation/tcd_latest.xsd

Change connectionconfig's children could be in random order.

Change connectionconfig's children could be in random order

---

docs/api-reference.md

**A Helpful Guide For Navigating Our Branches**
* If this is a hotfix, make your PR against `master`.
* If your change can ship immediately, make your PR against `dev-tdvt`.
* If your change is for a future release, make your PR against the appropriate holding branch (eg `dev-2020.1`)
_Also:_
* Please update the changelog of the project you modified, either under `vNext` or under a point release if you bumped the version.
* If you are merging into master, update the root `README.md` if the PR includes a release of the SDK, Connector Packager, or TDVT.
Thank you and feel free to delete this from your PR description!

update api doc to indicate map as return type for connection-properties

---

docs/api-reference.md

**A Helpful Guide For Navigating Our Branches**
* If this is a hotfix, make your PR against `master`.
* If your change can ship immediately, make your PR against `dev-tdvt`.
* If your change is for a future release, make your PR against the appropriate holding branch (eg `dev-2020.1`)
_Also:_
* Please update the changelog of the project you modified, either under `vNext` or under a point release if you bumped the version.
* If you are merging into master, update the root `README.md` if the PR includes a release of the SDK, Connector Packager, or TDVT.
Thank you and feel free to delete this from your PR description!

Fix api doc in 2019.4

---

docs/api-reference.md

Putting this in the 2020.1 holding branch for docs.

Add deprecated api doc

---

README.md

Updated issues after some were fixed in the recent maintenance release

---

connector-packager/CHANGELOG.md
connector-packager/connector_packager/helper.py
connector-packager/connector_packager/package.py

-detect duplicated options -d/--dest
-clean up unused import in helper.py
-update CHANGELOG.md

Improve command line argument parsing

---

README.md

Adds a link to the youtube recording of mine and Stephen's tc talk to the Getting Started section

Add tc talk to readme

---

docs/api-reference.md

Fix driver resolver doc bug

---

connector-packager/connector_packager/jar_jdk_packager.py
connector-packager/connector_packager/version.py
connector-packager/connector_packager/xml_parser.py
connector-packager/connector_packager/xsd_validator.py
connector-packager/tests/test_jar_packager.py
connector-packager/tests/test_resources/modular_dialog_connector/connectionBuilder.js
connector-packager/tests/test_resources/modular_dialog_connector/connectionFields.xml
connector-packager/tests/test_resources/modular_dialog_connector/connectionMetadata.xml
connector-packager/tests/test_resources/modular_dialog_connector/connectionProperties.js
connector-packager/tests/test_resources/modular_dialog_connector/connectionResolver.xml
connector-packager/tests/test_resources/modular_dialog_connector/dialect.xml
connector-packager/tests/test_resources/modular_dialog_connector/manifest.xml
connector-packager/tests/test_xml_parser.py
validation/connection_fields.xsd
validation/connector_plugin_manifest_latest.xsd
validation/connector_plugin_metadata.xsd

Adds XSD files for modular connection dialogs as well. Will add some unit tests as well.
Opening this against dev-2020.2 since this won't be able to be used until that release.

Add support for new dialog files in packager

---

docs/index.md

Update the documentation now that the readme is updated

Update JDBC driver requirements

---

docs/log-entries.md
docs/package-sign.md
docs/tdvt.md

Tdvt page: add minor descriptive infor for where to find targets.
Packaging page: add minor infor for target folder and basic info.
Logging page: add a subtitile that might need to be added.

Add minor descriptive updates to steps.

---

docs/mcd.md

Prefix `v-` for vendor defined field names

Document vendor defined attributes

---

_posts/2020-04-6-packaging-changes.md

Post about the packaging changes, since they are breaking. Once this is approved, will merge at the same time as https://github.com/tableau/connector-plugin-sdk/pull/475 and https://github.com/tableau/connector-plugin-sdk/pull/468

Add packaging changes post

---

docs/design.md
docs/dialect.md
docs/example.md
docs/index.md
docs/localize.md
docs/manual-test.md
docs/package-sign.md
docs/run-taco.md
docs/share.md
docs/tdvt.md
docs/ui.md

Docs dm 041520

---

README.md

Update readme for 2020.2 release

---

docs/run-taco.md

Tested this a bit ago. Doesn't require messing about with tsm options.

Update server instructions

---

CHANGELOG.md
samples/components/dialects/Annotated.tdd
samples/components/dialects/Hive12Dialect.tdd
samples/components/dialects/full_dialect.tdd

Remove all except the custom start of the week for date functions with `localstr` as the last argument. See https://github.com/tableau/connector-plugin-sdk/issues/505 for details

TFSID 888124 :[SDK] Update custom start of week date functions samples

---

docs/example.md

Issue : https://github.com/tableau/connector-plugin-sdk/issues/518 .
Tried rewording the statements to keep the intent but make it less confusing. Open to better re structuring of the statements.

Fix some wording on the example page regarding the .tcd and .tdr files

---

samples/plugins/postgres_jdbc/dialect.tdd
samples/plugins/postgres_jdbc/manifest.xml
samples/plugins/postgres_odbc/dialect.tdd
samples/plugins/postgres_odbc/manifest.xml

- Update samples: Postgres 9.0 Dialect as TDD
- Update min-version-tableau to 2020.3 for dialects
- Depends on XSD changes in [PR528](https://github.com/tableau/connector-plugin-sdk/pull/528)

Update postgres_odbc and postgres_jdbc samples to have tdd defined dialect 

---

docs/dialect.md

Update the documentation for date function and date parts.

TFS 888124: [SDK][Docs] Document dialect <date-function> and <date-parts>

---

docs/dialect.md

[SDK][Doc] Update dialect documentation page to describe join support

---

docs/dialect.md

Documentation for temp table and boolean support

---

_posts/2020-06-24-documentation-update.md
_posts/2020-06-25-new-release-2020-3(Beta).md
docs/mcd.md

TFS1132317: Create a whats new page for new documentation and SDK improvements in 2020.3

---

samples/Readme.md
samples/plugins/postgres_jdbc/Readme.md
samples/plugins/postgres_odbc/Readme.md
samples/scenarios/extract_only/sqlite_extract/Readme.md
samples/scenarios/mysql_based/mysql_odbc/Readme.md
samples/scenarios/vendor_attributes/postgres_vendor/Readme.md

Hopefully this makes it easier for partners to understand the purpose of the various samples we have.

Add sample readmes

---

docs/capabilities.md
docs/dialect.md
docs/mcd.md
docs/tdvt.md

-     Add documentation for TimeoutSeconds
-     Add documentation for CAP_QUERY_TIME_REQUIRES_CAST
-     Remove old documentation for function element being not recognized
-     Remove the alpha feature description from mcd

TFSID1117828 : Update documentation to add CAP_QUERY_TIME_REQUIRES_CAST, timeoutseconds and dialect  in github

---

tdvt/tdvt/tabquery.py
tdvt/tdvt/tdvt.py
tdvt/tdvt/tdvt_core.py

Update the tdvt parsing logic to handle password file in server version tests

Update tdvt for handling password file for server version test

---

docs/capabilities.md

- added additional supported ODBC and JDBC capabilities
- removed deprecated capability that was specific to internal scenario
- added Initial SQL capability for more granular connection dialog control

Updated documented capabilities.

---

docs/tdvt.md

Add commands to run the connector tests.
Some of the sample files required to run the commands are in PR right now : 
https://github.com/tableau/connector-plugin-sdk/pull/557
https://github.com/tableau/connector-plugin-sdk/pull/555

Add commands to run the connector tests.

---

README.md

I think this is the only place we have to update, let me know if I missed any

Update readme for 2020.3 release

---

docs/api-reference.md

Jade pointed out that this was confusing and made it seem like the bug was still active, and considering how long it took me to parse what this entry was trying to say despite knowing the topic I agree.

Clarify connection-properties description

---

_posts/2020-8-12-new-release-2020-3.md

Copied the new features from Saugat's beta blog from a while ago. Let me know if there is anything missing.

Add new 2020.3 release blog post

---

validation/tcd_latest.xsd
validation/tdd_latest.xsd

Sync XSD from 2020.3 release

---

CHANGELOG.md
samples/plugins/postgres_jdbc/dialect.tdd
samples/plugins/postgres_jdbc/manifest.xml
samples/plugins/postgres_odbc/dialect.tdd
samples/plugins/postgres_odbc/manifest.xml
validation/tdd_latest.xsd

Changes:
Add ISO8601 support to both dialects, same changes from this [CR](https://reviewboard.prod.tableautools.com/r/279269/diff/3/)

Add ISO8601 support to postgres_odbc and postgres_jdbc samples

---

docs/design.md

Update documentation to reflect the findings of how plugin versioning works.

Add information on plugin-versioning

---

tdvt/tdvt/resources.py
tdvt/tdvt/tdvt_core.py

Fixed path resolution for the metadata file and added error handling in case it's missing

Fix metadata file path

---

docs/design.md

Closed the last pull request by mistake.

 Add information on class isolation for JDBC driver 

---

docs/capabilities.md

Remove `CAP_ODBC_TRANSACTIONS_SUPPRESS_AUTO_COMMIT` from SDK doc

Remove CAP_ODBC_TRANSACTIONS_SUPPRESS_AUTO_COMMIT from SDK doc

---

_includes/docs_menu.html
docs/bug-artifacts.md

For TFS1172882
Not entirely sure the messaging we want for the expectations when people file a bug, open to suggestions on that. Hopefully this will cut down on us needing to constantly ask for logs.

Add filing a bug page

---

docs/tdvt.md

- Removed duplicate lines
- Added links to Python releases
* **`2020.2`**
=====

Installation doc improvements

---

docs/mcd.md

Add vendor related field names to documentation

Add vendor related field names to documentation

---

docs/example.md

Dmoynihan patch 3

---

docs/gallery-submission.md

Dmoynihan patch 4

---

docs/dialect.md

[SDK] TDD definition needs to say that format is distinct can give the wrong answer

---

docs/capabilities.md

- add additional capabilities developed during 2020.4 release
- some have been backported to latest maintenance releases as well
- documentation for CAP_ODBC_SUPPRESS_CATALOG_NAME added as part of a partner investigation

Document 2020.4 capability changes

---

docs/design.md
docs/dialect.md

TFS1206424: [SDK] Update docs to add the workaround for Join Issue in OLAP Cubes

---

docs/index.md
docs/mcd.md

Fix broken links

---

samples/scenarios/multi_auth/connectionBuilder.js
samples/scenarios/multi_auth/connectionFields.xml
samples/scenarios/multi_auth/connectionMetadata.xml
samples/scenarios/multi_auth/connectionProperties.js
samples/scenarios/multi_auth/connectionResolver.tdr
samples/scenarios/multi_auth/dialect.tdd
samples/scenarios/multi_auth/manifest.xml

A PostgreSQL connector that supports multiple authentication options using Connection Dialog V2 style [definition](https://tableau.github.io/connector-plugin-sdk/docs/mcd).
Demonstrates:
- selection field with default value
- conditional fields
- vendor field (v-)
- custom field labels
- optional field

Connection Dialog V2 scenario sample

---

connector-packager/connector_packager/jar_jdk_packager.py
connector-packager/tests/test_jar_packager.py

Bring my recent merge into dev-2021.1.

Merge master into dev-2021.1

---

connector-packager/connector_packager/jar_jdk_packager.py
connector-packager/connector_packager/xml_parser.py
connector-packager/connector_packager/xsd_validator.py
connector-packager/tests/test_jar_packager.py
connector-packager/tests/test_resources/oauth_connector/connectionBuilder.js
connector-packager/tests/test_resources/oauth_connector/connectionFields.xml
connector-packager/tests/test_resources/oauth_connector/connectionMetadata.xml
connector-packager/tests/test_resources/oauth_connector/connectionProperties.js
connector-packager/tests/test_resources/oauth_connector/connectionResolver.xml
connector-packager/tests/test_resources/oauth_connector/dialect.xml
connector-packager/tests/test_resources/oauth_connector/manifest.xml
connector-packager/tests/test_resources/oauth_connector/oauth-config.xml
connector-packager/tests/test_xml_parser.py
validation/oauth_config.xsd

Merging in dev-2021.1 branch right now, but can merge into a separate dev-oauth-wip branch if people think that's a better idea.

Support packaging OAuth connectors [wip]

---

docs/dialect.md

Not entirely sure this is the right place for this information, or if it should be under "Design Considerations".

Add default date information

---

docs/oauth.md

TFSID: 1183752 - [OAuth Service]Rename capabilities

---

samples/components/dialects/Hive12Dialect.tdd

The objective of this is to reproduce c++ Hive12Dialect in a sample tdd file.
I generated the tdd draft and went over all c++ functions of Hive12dialect and Hive dialect to fix some incorrect functions in tdd and added some sql-formatting.
Testing done: comparing tdvt result between built-in Hive12Dialect and my tdd, still in progress, I have completed all tests start with `"setup.date" `and `"setup.agg"`, all look good so far.

Update the Hive dialect sample

---

connector-packager/connector_packager/xml_parser.py

Add support for Italian in packager

---

docs/oauth.md
docs/tdvt.md

pssword file should support tokens.

---

docs/oauth.md

Add more instructions to add required Attrs for Pluggable OAuth.
* **`2020.2`**
=====

Add more instructions for oauth required attrs.

---

docs/manual-test.md

* **`2020.2`**
=====
Add a <br/> tag before each image to have them displayed on a separate line

Defect 1235346: [SDK] Manual QA Tests doc formatting issue

---

docs/manual-test.md

Defect 1235346: [SDK] Manual QA Tests doc formatting issue . Update lines missed in https://github.com/tableau/connector-plugin-sdk/pull/750

---

.github/pull_request_template.md
README.md

Update the readme and PR template to reflect the changes for the new release. 
Will merge dev-2021.1 to master once this is done.

Update PR template and Readme. 

---

index.html

The link to the community forums was broken. So I fixed it.
=====

Fixing a broken link to the community forums

---

_includes/docs_menu.html
docs/api-reference.md
docs/drivers.md
docs/index.md

Open to adding/removing SQLStates from the list of important ones. Had a few more on there before deciding to cut down to these 3.

Add driver requirements page

---

docs/metadata-enumeration.md

Add JDBC metadata enumeration section.

Add JDBC metadata enumeration section.

---

docs/drivers.md

Add links to ODBC and JDBC SQLSTATES lists

---

connector-packager/connector_packager/jar_jdk_packager.py
connector-packager/tests/test_jar_packager.py
connector-packager/tests/test_resources/tableau_support_link/manifest.xml

Tested manually, also added unit test

Set min-tableau-version to 2021.1 when tableau support link is used

---

docs/oauth.md

Updateto o auth doc

---

README.md

Update README.md with release

---

README.md
samples/scenarios/snowflake_oauth/oauthConfig.xml

Hopefully this correctly clears the last 2 conflicts.
It shows 92 commits for some reason in the PR, but will only have 1 commit once merged, like the previous PR I did yesterday. Git! Yay!

Pv/dev 2021.2 merge

---

_posts/2021-7-19-new-release-2021-2.md

Let me know if I'm missing any features for 2021.2

Add blog post for 2021.1 release

---

validation/tdd_latest.xsd

Update this dialect xsd as latest near, changes are from near file history 6-10(5 revisions in total)

update dialect xsd up to date

---

validation/tdd_latest.xsd

Update dev-2021.4's dialect xsd as latest near, changes are from near file history 6-10(5 revisions in total)

keep dialect xsd up to date

---

tdvt/tdvt/config_gen/gentests.py

This is for TFSID 942383.
Based on this LogicalConfig part of this [doc](https://tableau.github.io/connector-plugin-sdk/docs/tdvt) and tdvt test code, we should care about the value of those options are true or false, but in tdvt code here, it only checks if the key is present or not, without checking the value of it is true or false.

Fix tdvt logical query config loading

---

connector-packager/tests/test_resources/oauth_connector/oauth-config.xml
validation/oauth_config.xsd

remove clientIdServerCustom, clientSecretServerCustom, redirectUrisServerCustom for oauthConfig

remove *ServerCustom elements

---

samples/scenarios/snowflake_oauth/oauthConfig.xml

The capability names in oauthConfig.xml misses the "OAUTH_" prefix, which does not align with the ones in oauth-service.

update capabiliteis name in oauthConfig.xml

---

docs/localize.md

Update SDK doc `Localize Your Connector` with newly supported French (Canada).

Add French (Canada) to supported languages

---

validation/tdd_latest.xsd

- Created release for 2021.2
- Will send out another PR for gh-pages merging and post a blog post of the release updates after this

Merge Holding Branch

---

docs/capabilities.md

- Resolve conflict and merge the holding branch for docs for 2021.3

Merge holding dranch dev-2021.3 github pages

---

_posts/2021-09-13-new-release-2021-3.md

- Updated the what's new page for the released  version of 2021.2
- Did not see anything that should be included in the post for the 2021.3 release in the SDK that the customer should know in the docs update. Let me know if we should add the new capabilities we added in the 2021.3 docs here.

Gh pages stripathi

---

_includes/docs_menu.html
docs/design.md
docs/gallery-submission.md

Updating gallery name change to Tableau Exchange

---

docs/api-reference.md

Document GetProductName and GetProductVersion. Details in 1224977

Document product name and product version JavaScript APIs

---

docs/capabilities.md

- CAP_EXTRACT_ONLY_REFRESH
- CAP_CONNECT_NO_CUSTOM_SQL

Document additional existing capabilities 

---

samples/scenarios/extract_only/sqlite_extract/manifest.xml

- add now documented `CAP_EXTRACT_ONLY_REFRESH`

Enable extract refresh in SQLite sample

---

samples/components/dialects/Hive12Dialect.tdd
validation/tdd_latest.xsd

Looks like the hive dialect was the only thing that changed in 2021.4. Unfortunately, these are Jianan's changes and he's no longer on the team, so added some other people to double check that the changes are ok.

Merge dev-2021.4 into master

---

docs/tdvt.md

Included documentation regarding the new --output-dir option flag.
=====

Update tdvt.md for custom output directory

---

tdvt/test/tdvt_test.py

Remove python3 from docstrings

---

_posts/2022-03-31-new-release-2022-1.md
docs/dialect.md
docs/gallery-submission.md
docs/run-taco.md
docs/templates/tableau-server.md

Pull latest changes in gh-pages-dev-2022.2

Merge gh-pages into gh-pages-dev-2022.2

---

samples/components/dialects/FullFunctionMap.tdd

Standard argument combinations:
- DATEADD: localstr, int, datetime
- DATEDIFF: localstr, datetime, datetime and localstr, datetime, datetime, localstr
- DATENAME: localstr, datetime and localstr, datetime, localstr
- DATEPART: localstr, datetime and localstr, datetime, localstr
- DATETRUNC: localstr, datetime and localstr, datetime, localstr

Remove <date-function> with non-standard args

---

docs/capabilities.md

Two new capabilities for 2022.2

---

README.md
samples/components/dialects/FullFunctionMap.tdd

```
git checkout dev-2022.2
git pull
git checkout -b dev-2022.2-merge
git merge origin/master
git push -u origin dev-2022.2-merge
```

Merge origin/master into dev-2022.2

---

tdvt/tdvt/config_gen/test_creator.py
tdvt/tdvt/setup_env.py
tdvt/tdvt/tdvt_core.py

User setup for custom schema

---

docs/localize.md

Add supported language sv_SE

---

connector-packager/connector_packager/xml_parser.py
connector-packager/tests/test_xml_parser.py

Add new supported language sv_SE.
Reformatted a few strings.

Add new supported language sv_SE

---

docs/tdvt.md

OS region setting requirements for TDVT test

---

docs/connection-dialog.md

Update docs to clear connection cache

---

docs/tdvt.md

- Update documentation for running tabquerytoolsrv

Update documentation for running tdvt tests using tabquerytoolsrv

---

docs/oauth.md

TFSID: 1474151 - [OAuth Service] Redirect Uri should allow loopback addresses when loopback capability is enabled

---

CHANGELOG.md
connector-packager/connector_packager/jar_jdk_packager.py
connector-packager/tests/test_jar_packager.py
connector-packager/tests/test_resources/oauth_config_id/invalid/oauth-config.xml
connector-packager/tests/test_resources/oauth_config_id/valid/oauth-config.xml
connector-packager/tests/test_resources/oauth_connector/oauth-config-with-id.xml
connector-packager/tests/test_xsd_validator.py
validation/oauth_config.xsd

…rl fields
=====
TFSID 1470733: [OAuth] [Connector SDK] Update Connector SDK to contain updated version of OAuthConfig.xsd file for validation.

TFSID 1470733: [OAuth] [Connector SDK] Update Connector SDK to contain updated version of OAuthConfig.xsd file for validation.

---

connector-packager/connector_packager/xml_parser.py

Update xml_parser.py to add th_TH language

---

_posts/2022-10-18-new-release-2022-3.md
docs/api-reference.md
docs/auth-modes.md
docs/capabilities.md
docs/connection-dialog.md
docs/design.md
docs/dialect.md
docs/drivers.md
docs/example.md
docs/index.md
docs/localize.md
docs/log-entries.md
docs/manual-test.md
docs/mcd.md
docs/metadata-enumeration.md
docs/oauth.md
docs/package-sign.md
docs/run-taco.md
docs/security-considerations.md
docs/tdvt-test-case.md
docs/tdvt.md
docs/ui.md

```
git checkout gh-pages-dev-2022.4
git pull
git checkout -b gh-pages-dev-2022.4-merge
git merge origin/gh-pages
git push -u origin gh-pages-dev-2022.4-merge
```

Merge origin/gh-pages into gh-pages-dev-2022.4

---

docs/drivers.md

JDBC Documentation link was no longer accurate.

Update JDBC SQLState doc

---

docs/api-reference.md

Remove inferred connection resolver documentation until it can be improved and clarified.

remove inferred connection resolver doc

---

docs/design.md

Add mention that class cannot be changed, so we have something to link to in reviews when people try and change the class.

Update connector class documentation

---

_posts/2022-10-18-new-release-2022-3.md
_posts/2022-12-14-new-release-2022-4.md
docs/api-reference.md
docs/auth-modes.md
docs/capabilities.md
docs/connection-dialog.md
docs/design.md
docs/dialect.md
docs/drivers.md
docs/example.md
docs/index.md
docs/localize.md
docs/log-entries.md
docs/manual-test.md
docs/mcd.md
docs/metadata-enumeration.md
docs/oauth.md
docs/package-sign.md
docs/run-taco.md
docs/security-considerations.md
docs/tdvt-test-case.md
docs/tdvt.md
docs/ui.md

```
git checkout gh-pages-dev-2023.1
git pull
git checkout -b gh-pages-dev-2023.1-merge
git merge origin/gh-pages
git push -u origin gh-pages-dev-2023.1-merge
```

Merge origin/gh-pages into gh-pages-dev-2023.1

---

tdvt/tdvt/config/tdvt/tdvt.ini

Fixed spelling of Tableau in `tdvt/config/tdvt/tdvt.ini`

Fixed spelling of Tableau

---

tdvt/tdvt/config/tdvt/tdvt.ini
tdvt/tdvt/logicaltests/expected/lod/expected.setup.lod.16_As Group.2.xml

```
git checkout dev-2023.1
git pull
git checkout -b dev-2023.1-merge
git merge origin/master
git push -u origin dev-2023.1-merge
```

Merge origin/master into dev-2023.1

---

docs/tdvt.md

Documentation for custom schema feature

---

_includes/docs_menu.html
docs/common-errors.md

- Add docs page for common errors

@W-12316798: [SDK] [Documentation] Add "Common Errors" section to the SDK Docs

---

docs/oauth.md

Backport https://github.com/tableau/connector-plugin-sdk/pull/1106 to gh-pages/2023.1.

@W-12971206 - [OAuth][SDK] Backport `instanceUrlSuffix` support to 2023.1

---

docs/oauth.md

Remove the confusing statement in oauth md
=====

W-13486557: [SDK][Github Issue 1129][BUG] Misleading <redirectUrisDesktop> with dynamic port support

---

tdvt/TDVT Results.twb
tdvt/tdvt/config_gen/datasource_list.py

Fixed the join and added visual filters for functions and test categories.

@W-12315436S [SDK] Refresh TDVT workbook sdavis-tdvt-twb

---

docs/gallery-submission.md

Gallery submission doc updates

---

docs/gallery-submission.md

Updates to GTM section on the gallery-submission.md

---

_includes/docs_menu.html
docs/oauth-dev.md
docs/oauth.md

Fix the sidebar TOC

---

samples/components/oauth/athena.okta.xml
samples/components/oauth/redshift.azure.xml

we should recommend enabling pkce and state in samples

W-14059989 - [OAuth] Update oauth samples in sdk

---

.github/ISSUE_TEMPLATE/bug_report.md

Add link to bug report documentation page

Update bug_report.md with link to docs

---

README.md

Update readme
Would we like to start linking to previous releases in `README.md`? If no, I'll remove the link.
Depends on #1195 and #1196

Update README.md for release

---

README.md

Update python version in main readme

---

docs/oauth.md

- Explain that you need to restart TD to pick up changes.
- Fix a typo
- Remove quotes for directories which are also in backticks.

Minor changes

---

tdvt/TDVT Results.twb

As part of hackathon, I made some changes to the TDVT workbook to fix some pet peeves I have on it, most of these are changes I make locally every time. I ended up massively simplifying the workbook instead of my original attempt to add more detailed views and fix existing ones - in my experience reviewing TDVT results, having the one table of test cases with the useful columns and good filters is more useful in this case than lots of dashboards.
Changes:
- Fixed a couple duplicate columns
- Removed some dashboards/sheets I found confusing and not useful, they seemed unfinished and redundant. Now the only tabs are the main overview and the details tab
- Added many useful columns to the details tab, like the functions the test uses, the test name, and the priority. Also added these as …

Revise TDVT workbook

---

samples/components/oauth/snowflake.azure.xml

add snowflake external oauth sample

---

docs/oauth.md

Jkean w 16913162 add token note

---

docs/oauth.md

Updating note warning that single use tokens are not supported at this time.

jkean-W-17177926-upd-singletoken-doc

---

docs/oauth.md

@W-13807634, Clarify OAuth docs for single use refresh tokens
