README.md
The `Why Connectors` link in our README's table of contents doesn't have a target and 404s when clicked.
=> Fix missing link in README

tdvt/tdvt/tdvt_core.py
At the moment our code will attempt to perform subtraction on `len(None)`, which throws a TypeError. This is a small PR to (a) stop tdvt from trying to find the length of `None` or do math on `None`, while giving good error messages.
=> Remove math on None

js/search.js
When displaying a user's search query on the search results page, we should use `textContent` instead of `innerHTML` to prevent XSS per [this OWASP cheatsheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.md#rule-6---populate-the-dom-using-safe-javascript-functions-or-properties).
Note: This change is already in `gh-pages-dev`.
=> [Security] Fix docs XSS vulnerability in search

samples/plugins/postgres_jdbc/manifest.xml, samples/plugins/postgres_odbc/manifest.xml
Add the newly required company name and support link to the samples for 2019.2. I'll update the docs as well to explain a bit of the why.
=> Add company name and support link to samples

docs/example.md
Updated the examples page to document the new company name and support link requirements in the manifest file.
=> Add vendor information info to Examples page

packaging/package.py, packaging/packaging/xsd_validator.py
Initial stub. I added the XSD validator as a separate file, and used TDVT as a guide for setting that up to put that in a module we can import from.
=> Create stub for XSD Validation

packaging/package/jar_packager.py, packaging/package/package.py
According to the readme, we should be running this from connector-plugin-sdk/packaging, but package.py and jar_packager.py would not find the imports if run from there.
=> Fix so that all modules run from same location

packaging/package/jar_packager.py, packaging/package/package.py, packaging/package/xsd_validator.py, packaging/tests/__init__.py, packaging/tests/test_xsd_validator.py
Changes most print statements to logging.debug. There are a few I made warnings. This means that, unless verbose is set to true via a command line argument, we do not print it to the console. (It's hardcoded right now since we haven't set that up yet.) We will, however, always save it all log messages to packaging_log.txt. 
Let me know if there are some messages that should be shown to the console that I have labeled as debug.
=> Add logging instead of print statements

packaging/package/package.py
(.venv) PS connector-plugin-sdk\packaging> python -m package.package -h
usage: package.py [-h] [-v] [-l LOG_PATH] [--validate_only] [-d DEST]
[-n NAME]
input_dir
Tableau Connector Packaging Tool: package connector files into a singe Tableau
Connector (.taco) file.
positional arguments:
input_dir             path to directory of connector files to package
optional arguments:
-h, --help            show this help message and exit
-v, --verbose         verbose output
-l LOG_PATH, --log LOG_PATH
path of logging output
--validate_only       runs package validation steps only
-d DEST, --dest DEST  destination folder for packaged connector
-n NAME, --name NAME  name of the packaged connector
=> Refactor argparse usage, simplify main

packaging/package/jar_jdk_packager.py
1. change logger.debug to logger.error
2. use executable file existing or not to judge path jdk setup, instead of regular expression pattern match.
=> change logger.debug to logger.error, and judge executable file exist or not

.pep8speaks.yml
Starting [pep8speaks](https://pep8speaks.org) with a pretty light touch. The code inspector will only look at _new_ code - won't go through the whole project and list violations.
Over time we can add error codes to be ignored if it gets annoying.
=> add .pep8speaks.yml

packaging/README.md, packaging/package/package.py, packaging/tests/test_package.py
Allowing tool to rename at packaging time implies functionality we do not intend to support.  1:1 classAttr:packageFile for now.
=> Remove -n name argument

tdvt/tdvt/tdvt.py, tdvt/tdvt/tdvt_core.py
Make changes to the log zip file organization so it will be as follows:
`tabquery_logs.zip/test_type_suite_name/<'log*.txt'/'tabprotosrv*.txt'/'crashdumps/*'>`
`tdvt_actuals_combined.zip/test_type_suite_name/*actuals`
(click to enlarge)
=> Improve TDVT log organization

tdvt/tdvt/tdvt_core.py, tdvt/tdvt/test_results.py
Create dummy test cases when creating a TestResult. There is only one test case per logical test, but expression tests can have multiples, so parse the setup file and count them.
Verified that tests counts don't change if they pass, fail, or are aborted.
=> Fix test counts

packaging/package/helper.py, packaging/package/jar_jdk_packager.py, packaging/package/jar_jdk_signer.py, packaging/package/package.py
Changes:
1. Add jar_jdk_signer package, and call it from package.py
2. Add a helper package, move package.init_logging function and jar_jdk_packager.check_jdk_environ_variable function to helper.
3. Add a few command arguments for signing use 
Command to do packaging and signing:
py -3 -m package.package E:\Github\testdir\postgres_odbc -a jsun -ks "C:\Program Files\Java\jdk1.8.0_201\jre\lib\security\testdir\jsun.jks"
Command to do packaging only:
py -3 -m package.package E:\Github\testdir\postgres_odbc --package-only
=> Add signing functionality

.pep8speaks.yml, packaging/README.md, packaging/package/jar_jdk_packager.py, packaging/package/jar_jdk_signer.py, packaging/package/package.py, packaging/package/xml_parser.py
This PR does the following:
* Change the `--log` arg. Previously it took a path to a specific file. Now, it does what the label says, and accepts a path to where the file is saved.
* Raises a warning at the command line and in the logs when `--validate-only` and `--package-only` are run together.
* Minor changes to README
* Brings in pep8speaks so it'll stop nagging us about 120 char lines
There are whitespace changes in this PR; you can have GitHub ignore them by selecting the following:
=> Packaging tool improvements before shipping

docs/tdvt.md
`boolUnderscore` isn't in the code; `bool_underscore` is, in [`tdvt/tdvt/config_gen/gentests.py`](https://github.com/tableau/connector-plugin-sdk/blob/dev/tdvt/tdvt/config_gen/gentests.py#L61). `bool_underscore` is also in the .ini files for dbs like mysql, which make use of this.
**Pro tip:** When looking at the `Files changes` tab, click on the document icon for a nicer diff!
=> REFACTOR: boolUnderscore to bool_underscore

docs/auth-modes.md
Document the supported auth modes with sample connection dialog, connection resolver.  Also include notes about the hive specific constraints.
=> Initial Authentication Modes doc

connector-packager/connector_packager/jar_jdk_packager.py, connector-packager/connector_packager/version.py, connector-packager/tests/test_jar_packager.py
Stamp min support tableau version while packaging(updated)
- Do the stamping after packaging
- Make a copy of the original manifest file, after packaging, recover it to keep original manifest unchanged 
Test it: 
py -3 -m connector_packager.package tests\test_resources\valid_connector --package-only
=> Stamp min support tableau version while packaging

tdvt/tdvt/config_gen/datasource_list.py
missing `get_is_test_enabled`, just passing a weird tuple
=> REFACTOR add missing function call

tdvt/tdvt/tabquery.py, tdvt/test/tdvt_test.py
We have completed a new feature planned to turn on for 19.4. There is a rewrite rule added which has to work with RewriteConstantFuncall which is disabled in TDVT tests, so we also need to disable this one since it would cause some SQL text unable to be executed in DB2.
=> TFSID952474: Disable Aggregate:MoveGroupBysToMeasures since FuncallRewrite:RewriteConstantFuncall is also disabled

tdvt/tdvt/config/tdvt/tdvt.ini, tdvt/tdvt/config_gen/datasource_list.py, tdvt/tdvt/config_gen/tdvtconfig.py, tdvt/tdvt/config_gen/test_config.py, tdvt/tdvt/tdvt.py, tdvt/tdvt/tdvt_core.py
Added custom timeout seconds feature in tdvt by updating the config file(ini) for a particular plugin.
To set the custom time out in seconds, you will need to add TimeoutSeconds attribute in [Datasource Section]
For example:
[Datasource]
Name = vertica
LogicalQueryFormat = prefix
CommandLineOverride = -DOverride=ISO8601DateAddDiffYearQtr
TimeoutSeconds = 7200
=> TFSID: 952729 - [TDVT][Alibaba] Update TDVT to take custom value for timeout

tdvt/tdvt/tdvt.py
If the test fails in teamcity and succeeds on retry, we will add the test to the successful tests, but not remove it from the failed test list in tdvt_ouput_combined.json. I think this is why teamcity counts the test cases that succeed on retry as failed. This commit will strip out the failed test if it is in the newly succeeding tests.
=> Remove failed tests if they succeed on retry

samples/plugins/mysql_odbc/connectionResolver.tdr, samples/plugins/postgres_jdbc/connectionResolver.tdr, samples/plugins/postgres_odbc/connectionResolver.tdr
For the 2019.4 partner-built plugins, this was something I had to add to all of them.
=> Add initial sql + impersonate attributes to samples

docs/design.md, docs/example.md, docs/index.md, docs/share.md
- Removed outdated section on web authoring
- Changed headings of resolver methods since the normalizer might not be a .js file
- Change normalizer example to the recommended xml implementation
- Highlight that odbc and jdbc need a dialect file
- Change name of "Share your connector" page to "Run your connector". The most it says about sharing is "don't do it" since it's in beta, and actually running the connector is a bit hidden even with Logan's addition to the getting started page. This is the one I'm not as sure of, I'm open to suggestions on the best way to highlight running the connector (maybe split it into two separate pages?)
=> Documentation tweaks

connector-packager/connector_packager/package.py, connector-packager/connector_packager/xml_parser.py
Thanks to Sonia for finding this. Tracking it as TFS 1009026 internally.
Before we add the file to the list of files to package, check that that file exists and mark connector as invalid. There is a backup check after the file list is generated just in case.
Also took this opportunity to clean up some of the code around the validate-only flag.
=> Check that file exists before packaging it

connector-packager/connector_packager/helper.py, connector-packager/connector_packager/jar_jdk_packager.py, connector-packager/connector_packager/jar_jdk_signer.py
- changed the path separator character to use the os-specific one
- Removed the .exe from the executable name variables, only adding them back in if it's windows. (Haven't tested it yet, but this should also work for linux.)
Tested on both windows and mac, the test suite passes on both.
=> Mac packager fix

connector-packager/connector_packager/helper.py, connector-packager/connector_packager/xsd_validator.py
Our logger was not actually logging anything – [per this Stack Overflow thread](https://stackoverflow.com/a/53553516/3389827) I fixed by reloading the `logging` module before calling `.basicConfig`.
=> Fix logging bug in packaging tool

CHANGELOG.md, samples/plugins/mysql_odbc/connectionResolver.tdr, samples/plugins/postgres_jdbc/connectionResolver.tdr, samples/plugins/postgres_odbc/connectionResolver.tdr, samples/plugins/sqlite_extract/connectionResolver.xml
one-time-sql is added in the c++ code (like class is). Double-checked the connection strings for 2019.4 to make sure it was being properly propagated. Since it will be added to every plugin, it is redundant to add it in the tdr.
=> Remove one time sql

CHANGELOG.md, samples/plugins/mysql_odbc/connectionBuilder.js, samples/plugins/mysql_odbc/connectionDialog.tcd, samples/plugins/mysql_odbc/connectionResolver.tdr
Our sample connector did not disable ssl properly. Since it was trivial, added the ssl checkbox. Removed the 5.3 driver from the driver resolver since it'd need different logic for the ssl mode parameters and it is past EOL.
=> Fix MySQL Sample ssl

connector-packager/CHANGELOG.md, connector-packager/connector_packager/package.py
Ref: TFS1025155
Updates `connector-packager` to check if the logging directory exists. If it does not, the directory is created. Includes error handling for not being able to create the dir.
Since this happens _before_ logging is initialized, the updated code just prints to console rather than using `logging`.
Also, updated `log_file` to be a `Path` object. I'm not opposed to reverting it to string if that'd be better. I'm not sure that we get much out of making it a Path obj, tbh.
=> Update packaging logger to create logging dir if it does not exist

tdvt/CHANGELOG.md, tdvt/tdvt/tdvt.py
Keep all .txt and .log files including jdbc server log. Remove unneeded imports. Actually compress the log zip file.
Standardize help descriptions.
=> Keep all .txt and .log files including jdbc server log.

tdvt/CHANGELOG.md, tdvt/tdvt/tdvt.py
allows run-file to work again
testing done:
=> fix run-file command

tdvt/tdvt/config_gen/datasource_list.py, tdvt/tdvt/config_gen/test_config.py, tdvt/tdvt/tabquery.py, tdvt/tdvt/tabquery_path.py, tdvt/tdvt/tdvt.py, tdvt/tdvt/tdvt_core.py, tdvt/test/tdvt_test.py
Check for tabquery path before running unit tests that need it.
Cache list of tests for test_set. Fixed bug where run-pattern would take several seconds to run 0 tests.
=> Dev tdvt lriggs

tdvt/tdvt/exprtests/snowflake/datename/expected.setup.date.datename.month.txt, tdvt/tdvt/exprtests/snowflake/datename/setup.date.datename.month.txt
I changed the MON dialect to MMMM so that we return "Decemeber" instead of "Dec" when using TO_CHAR(datename)
see: Full name is the convention we document for Tableau calcs: https://help.tableau.com/current/pro/desktop/en-us/functions_functions_typeconversion.htm.  MMMM is the correct one to use here over MON and https://docs.snowflake.net/manuals/sql-reference/functions-conversion.html#label-date-time-format-conversion
Added in tests to snowflake to test that we are not truncating months in the datename function
=> TFSID 1040094: Add in new tdvt test files to test snowflake datename does not truncate

samples/plugins/postgres_jdbc/connectionProperties.js
Update Postgres JDBC example to use new properties map return type.
Manual test the sample connector can be loaded.
=> Update Postgres JDBC example to use new properties map return type

tdvt/CHANGELOG.md, tdvt/tdvt/exprtests/standard/expected.setup.string.contains.regex.txt, tdvt/tdvt/exprtests/standard/setup.string.contains.regex.txt
Tests the escaping of regex special characters in the contains function, this would have caught the databricks bug.
=> Add string.contains.regex test

samples/plugins/mysql_odbc/manifest.xml, samples/plugins/postgres_jdbc/manifest.xml, samples/plugins/postgres_odbc/manifest.xml
Right now these cannot be packaged with the packager change to enforce https. Doing this as a hotfix since it's technically a regression.
=> Make sample links https

docs/index.md
Just a small tweak -realized that the Getting Started page did not have all of the prerequisites in the "Before you Begin" section.
=> Update prerequisites in docs

README.md
Advertise Tableau's JDBC requirements. These are taken from https://help.tableau.com/current/pro/desktop/en-us/examples_otherdatabases_jdbc.htm.
=> Update JDBC driver requirement

docs/design.md
Tucker pointed out that we have a postgres superclass example about a paragraph before we list the only 3 superclasses we support, a list that does not include postgres. Re-wrote this section to reflect the fact that we want people to really only use odbc or jdbc. Also removed the example completely, as it is no longer valid.
=> Remove postgres superclass sample from design doc

_includes/footer.html
Updating the static copyright date with a script. 
We are making the same change on Tableau GitHub projects
=> Updating copyright date with script

README.md
Make it clear that the SDK is currently targeting 2020.1. In the future, we should look at making this process automatic and transparent.
=> Add version disclaimer

docs/mcd.md
Modular connection dialog field name attribute documentation.
This is the minimal set of name and value field information for platform integration:
- Endpoint
- SSL
- Authentication
This is the most concise way I found to communicate the core platform requirements.  I did not try to document the entire set of reserved connection attributes and values that was compiled here: https://gitlab.tableausoftware.com/connectivity/connector-plugin-sdk-internal/blob/master/docs/attributes.md
I'd be open to people's thoughts on the best way to communicate the entire set of reserved attributes.  I'll open anything like that in a follow-up change.
=> Field name attribute documentation 

docs/mcd.md
Most HTML elements are not supported in gh-pages markdown: remove and reformat list elements
Remove broken links to sub-heading, also unsupported in gh-pages markdown
=> Field name attribute formatting fixes

_layouts/news.html, _posts/2020-03-31-new-release.md, index.html, news/index.md
I need to beef up the post a bit, but this adds a news section that we can post to. I've tested locally, will try and get it to be visible to other computers as well. You can get a good idea of what it looks like from here (since I borrowed a lot of code from it): https://tableau.github.io/webdataconnector/news/
=> Add news section and initial post

connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_resources/broken_xml/connectionFields.xml, connector-packager/tests/test_resources/modular_dialog_connector/connectionResolver.xml, connector-packager/tests/test_xsd_validator.py
See documentation in 'Connection Field Platform Integration' section of [Connection Dialog V2](https://tableau.github.io/connector-plugin-sdk/docs/mcd) 
Enforce allowed names: server, port, sslmode, authentication, username, password or prefix v-
More details in TFS1092438.
=> Enforce platform reserved Connection Field name values 

docs/package-sign.md, docs/run-taco.md
Since we're removing signing from the packager, we also need to change the documentation to match. Also clarified a couple of things on disabling taco verification.
The main feedback I'd like is if I went too much in the direction of having little documentation on the process of signing the taco. Even though that was kind of the point, I still want to make sure they have some direction.
=> Refactor signing documentation

docs/index.md, docs/tdvt.md
There's been customer confusion around 2019.2 running taco files, so made improvement to index.md to help clarify requirement of 19.4.
Additionally, made one small change in tdvt config example
=> gh-pages Improvements

_includes/footer.html, css/main.css
Doc update:
- For GDPR compliance, adding legal and privacy links
- Updating styles and formatting of copyright text
=> Adding legal and privacy links to footer

validation/tdd_latest.xsd
'format-true' and 'format-false' are used in two use cases: literals and predicates
Literals: when a boolean is used a value
- defaults to x ? 1 : 0
- example usage: SELECT 1 as literalBool
Predicates: when a boolean is used as a predicate
- defaults to isTrue ? (1=1) : (1=0)
- example usage: SELECT something as blah WHERE (1=1)
- 'value' attribute is used as 'predicate' for backwards compatability
=> Update dialect XSD for 'format-true' and 'format-false' to allow literal, predicate and value attributes

docs/dialect.md
Add a section under the date-functions for dateparse as it is a little different from the other usual date functions.
Kept it a little short, like the other paras on the page and also linked an example of dateparse from Annoteted.tdd file for now . We may want to re-link it to the postgres_odbc or postgres_jdbc that will be added in future if required. Also tried to explain a little based off the example so its better to understand,
=> Add documentataion for DATEPARSE

CHANGELOG.md, samples/components/dialects/Annotated.tdd
This is unreferenced in the code.  Intended functionality is exposed in <format-column-definition>
=> TFSID1121798: [SDK][Docs] remove 'base-types' from tdd samples

CHANGELOG.md, samples/components/dialects/SQLDialect.tdd
Add SQLDialect to dialect examples to capture all implementation in BaseDialect\SQLDialect.
Manual tested tableau desktop can load this tdd, no syntax errors.
Methods in SQLDialect that can not be captured:
1. Methods are not part of dialect, these methods serve as a helper method for individual dialect to use.
AddNativeSplitFunction
AddRecursiveSplitFunction
GetIfThenElseFormula
NoCaseAliasLessThan
BinaryAliasLessThan
TruncateRemoteAlias
FormatInsertParameterMarker
GetParameterMarkers
FormatBulkInsert
AddFunctionRaw
HexEncodeNonAscii
ReplaceInvalidAscii
2. TDD doesn't support those functions now, and these methods are only overridden by a few dialects.
GetAliasLessThanFunc
FormatInitialSQL 
FormatInsertDataValue DataValueFormatter is partially covered in tdd
FormatUnion
FormatRange …
=> Add SQLDialect to dialect examples

docs/dialect.md
Add some documentation for the format-string-literal change I made a while ago.
There's also a bunch of whitespace changes, since I have my VSCode trim trailing spaces when I save I think. Doesn't look like anything actually changed, but the diff is a bit squirrely.
=> Add format-string-literal documentation

docs/auth-modes.md
- standardize auth mode values in examples
- add authentication as a required attribute in all cases
- update broken link
=> Update auth-modes page to use new auth constants

connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_resources/advanced_required_missing_default/connectionFields.xml, connector-packager/tests/test_resources/modular_dialog_connector/connectionFields.xml, connector-packager/tests/test_xsd_validator.py
This kind of requirement isn't really enforceable in XSD, so I added it in the python validator.
=> Added validation rule enforcing default values for non-optional fields in the advanced category

tdvt/tdvt/config/tdvt/tdvt.ini, tdvt/tdvt/tabquery.py, tdvt/tdvt/tdvt.py, tdvt/tdvt/tdvt_core.py
Based off a discussion with luke on the present flow of control for tdvt which heavily relies on BatchWorkQueue to run all the current datasource specific tdvt tests, adding a separate flow for running the connector tests which does not require any of those and only needs two arguments seemed as the cleanest way forward.
This code review is based on that discussion.
Tested by running the tests from tdvt and the results were as expected and the same as that run using tabquerycli directly.
=> Add commands in tdvt to run the connectors test command already added to tabquerycli

validation/tdd_latest.xsd
Add ISO8601 Aggregations to xsd, monolith has been updated, send this PR to keep 2020.4 up to date.
=> Add ISO8601 Aggregations to xsd

CHANGELOG.md, validation/tcd_latest.xsd
Addresses issue #561 by adding custom vendor properties to validation schema (of form `vendorx-prompt`), to properly validate connectors using custom vendor properties
+CHANGELOG.md update
=> Add elements to XML schema for validating custom vendor properties

_includes/docs_menu.html, docs/mcd.md, docs/ui.md
I'm not sure the best way to differentiate between the old style of connection dialogs and modular dialogs, which we call Connection Dialogs v2 externally. Calling the old syle "Legacy", should it be "deprecated"?
Diff looks bigger than it is since my VSCode removes trailing spaces on save.
=> Add mcd documentation to index

CHANGELOG.md, validation/connector_plugin_manifest_latest.xsd
Fixes #571 by validating the length of company name field in manifest.xml
And update CHANGELOG.md
Submitting on behalf of Goldman Sachs
=> Validate length of company name in manifest

tdvt/samples/config/all_options_example.ini
The documentation for TDVT has a gigantic 90-line ini file as the only documentation for how to make one of these. It's large and intimidating, and is hard to parse when trying to figure out something specific.
As part of my TDVT doc update, I'm rewriting that section and removing this giant blob of text. However, this may still be useful to people to see the syntax or something, so I'm adding it as a standalone example file.
=> Add all_options.ini sample

tdvt/CHANGELOG.md, tdvt/tdvt/resources.py, tdvt/tdvt/tdvt_core.py, tdvt/tdvt/test_results.py
- Added metadata struct that keeps track of priority, functions, and categories for a single test
- Load a map of test names to TestMetadata from test_metadata.csv
- Include these metadata fields in the test output
- Refactor some related test result functions
=> Add metadata to results

tdvt/CHANGELOG.md, tdvt/tdvt/tdvt.py, tdvt/tdvt/tdvt_core.py, tdvt/tdvt/test_results.py
Added an intermediary list to store test results instead of copying straight to the final output. Lists in python are thread-safe, so there shouldn't be any threading issues. The results are then sorted by the distinct number of functions tested.
=> Sort test results by complexity (number of functions tested)

tdvt/samples/config/all_options_example.ini
config had two `[Standard Tests]` sections which caused the list command to break when run in the samples dir.
=> fix broken config

samples/plugins/postgres_jdbc/connectionResolver.tdr, samples/plugins/postgres_odbc/connectionResolver.tdr, samples/scenarios/db_impersonation/connectionResolver.tdr, samples/scenarios/extract_only/sqlite_extract/connectionResolver.xml, samples/scenarios/mysql_based/mysql_odbc/connectionResolver.tdr, samples/scenarios/vendor_attributes/postgres_vendor/connectionResolver.tdr
Remove references to setImpersonateAttributes  from samples as it is already done in product code and there is no need to add it to the plugin code
=> Remove references to setImpersonateAttributes  from samples

connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_resources/modular_dialog_connector/connectionFields.xml
DataConnectionAttrs::attrVendor1, 2, 3 were added for plugin authors in connection dialog v1.  They have no platform meaning but are reserved to be used by plugins. Add these field names to the list of allowed fields so that the packager does not flag it as invalid and validation goes through successfully.
Tested by running the command locally : 
`D:\dev\git\connector-plugin-sdk\connector-packager>python -m connector_packager.package --validate-only D:\dev\git\connector-plugin-sdk\connector-packager\tests\test_resources\modular_dialog_connector
The log path D:\dev\git\connector-plugin-sdk\connector-packager exists
Validation succeeded.`
=> Update allowed field names to include vendor1, vendor2 and vendor3

docs/run-taco.md, docs/share.md
Also seems to have wiped out some trailing whitepsace, I have my visual studio set to remove that automatically. I'm really only changing one line in the two files.
=> Specify dev path connectors must be on same drive

docs/design.md
This change is for [TFS 1198120](https://tfs.tsi.lan/tfs/DefaultCollection/Tableau-Dev/_workitems/edit/1198920) 
The goal is to remove ProgressOpenEdgeDialect as a base dialect, and a few minor changes on how to create dialect.
=> remove ProgressOpenEdgeDialect as base dialect

connector-packager/connector_packager/jar_jdk_packager.py, connector-packager/tests/test_jar_packager.py
Also shows the version we stamp, and why. 
`(.venv) D:\connector-plugin-sdk\connector-packager>python -m connector_packager.package D:\connector-plugin-sdk\samples\scenarios\multi_auth
The log path D:\connector-plugin-sdk\connector-packager exists
Validation succeeded.
Detected minimum Tableau version required: 2020.3
-Connector uses Connection Dialogs V2, which was added in the 2020.3 release
Taco packaged. To sign taco file, use jarsigner.`
=> Update min version for dialogs v2

CHANGELOG.md, samples/components/dialogs/new_text_field/connection-dialog.tcd, samples/components/dialogs/new_text_field/connectionRequired.js, samples/components/dialogs/new_text_field/connectionResolver.tdr, validation/tdr_latest.xsd
The script based normalizer and matcher was previously deprecated with 2020.3 release.  This change removes support with XSD changes that will enforce it is not used during packaging.
- update XSD with **breaking change** for packaging enforcement
- previously usage of this pattern was removed from the samples, but new_text_field was missed, update it
- update changelog with description 
- remove the notion of Unreleased for the changelog, it doesn't make much sense with the current branching structure
=> Remove support for non-declarative normalizer and matcher

docs/capabilities.md
This was incorrectly documented as supported as a part of 2020.4 release.  Capability is removed in 2021.1.
=> Remove CAP_JDBC_BIND_UNKNOWN_COLUMNS

docs/package-sign.md
Add documentation about signing using timestamps, and call out the fact that tacos with expired certs will not be usable.
=> Add timestamp documentation

docs/api-reference.md, docs/example.md, docs/ui.md
Mentioned inferred connection resolver to both places connection-resolver is documented in the SDK.  Also fixed a few typos.  See individual commits for details.
=> Document inferred connection resolver

connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_resources/instanceurl/connectionFields.xml, connector-packager/tests/test_xsd_validator.py
Field 'instanceurl' is only supported when used with 'authentication'='oauth'.
- add check to packager
- add tests for positive and negative case
All tests pass: `python setup.py test`
There might be a more compact way to write this check.  Please suggest if so, thanks!
=> Enforce OAuth instanceurl usage in packager

tdvt/CHANGELOG.md, tdvt/tdvt/config_gen/gentests.py
If you add the following to your logical query config:
`fieldnamePostfix = __C`
The fieldnames will have `__C` appended to the end (ie str0__C)
=> Add a logical query option for fieldnamePostfix

tdvt/tdvt/exprtests/standard/expected.setup.operator.date.6.txt
The change in expected file is needed to enable running Presto TDVT tests in StandardDBs. 
I can create a new expected file if this will break existing customer's plugin test pipeline or nightly test ?? (need guidance on that )
=> Defect 1140212: [TDVT] [Presto] Intermittent test failures around Date

docs/dialect.md
Added info about format-date-literal and format-datetime-literal. I'm also going to make a monolith change to give these reasonable defaults, since we're no longer recommending DefaultSQLDialect as a base.
=> Add date formatting section to dialect docs

tdvt/tdvt/tdvt_core.py
Forgot to merge https://github.com/tableau/connector-plugin-sdk/pull/495 for about a year. Opening a new pull request since resolving the merge conflicts would be messier. 
Original description:
Had a tdvt results csv file that became very large since the process output was very large (~20,000 characters). Wrote a check that truncates to 512 [changed to 1024 in new PR] characters instead. Open to ideas of what the cutoff point should be, it may be a bit restrictive as of now.
=> Truncate long cmd_output

docs/tdvt.md
Added the new fieldnamePostfix option to the documentation on logical query format. Removed the calculated field workaround for not being able to change column names, since while it worked in expression tests it didn't work in the logical tests.
=> Add fieldnamePostfix doc change, remove column rename workaround

tdvt/CHANGELOG.md
The clac_data change didn't make it to 2.3.2 release in artifactory, putting it back under unreleased
=> Fix changelog

connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_resources/defaultSQLDialect_as_base/dialect.tdd, connector-packager/tests/test_xsd_validator.py
The packager warns the partner when they are using DefaultSQLDialect that DefaultSQLDialect isn't recommended.
Manually tested it with empty base, DefaultSQLDialect as base, and regular base, worked as expected.
=> Packager warn during validation about using DefaultSQLDialect

samples/components/dialogs/new_text_field/connection-dialog.tcd, samples/components/resolvers/simple_example.tdr, samples/plugins/postgres_jdbc/connection-dialog.tcd, samples/plugins/postgres_jdbc/connectionResolver.tdr, samples/plugins/postgres_odbc/connection-dialog.tcd, samples/plugins/postgres_odbc/connectionResolver.tdr, samples/scenarios/vendor_attributes/postgres_vendor/connection-dialog.tcd, samples/scenarios/vendor_attributes/postgres_vendor/connectionResolver.tdr
In username password scenarios
- 'authentication' should be in `required-attributes` list 
- .tcd UsernameAndPassword option value should be `auth-user-pass`
Documentation reference used: https://tableau.github.io/connector-plugin-sdk/docs/auth-modes
=> Align samples with documentation recommendations

docs/capabilities.md
Remove internal/deprecated JDBC capabilities, and add new ones.
Most of the new ones are for 2021.2, but I found a couple from earlier versions that were not present.
I'm not sure when CAP_JDBC_METADATA_SUPPRESS_PREPARED_QUERY was added, it's been there for a while.
This is a PR to master, I didn't realize there was a gh-pages branch for 2021.2. Will cherry pick this back later.
=> Remove internal/deprecated JDBC caps, and add new ones for 2021.2

docs/capabilities.md
These were implemented in such a way that they are coupled to the Hana connector. May change later.
=> Remove JDBC prepare caps from docs

tdvt/CHANGELOG.md, tdvt/MANIFEST.in, tdvt/tdvt/metadata/test_metadata.csv
This supersedes my previous MR. Added the metadata file dir to the setup manifest and cleaned it up quite a bit. There are way too many tests to audit individually (a road I tried going down before), but I made sure each function was at least mapped to a correct set of categories.
=> Clean up metadata

docs/oauth.md
=> Fixed Oauth doc formatting

_includes/docs_menu.html
Typo means clicking on the driver requirements page link on the index gives a 404 error.
=> Fix drivers page link

docs/design.md
Don't need this now that the new driver page is up. Diff is a bit strange because my VSCode automatically removes trailing whitespace.
=> Remove redundant driver information

docs/api-reference.md
Documented as deprecated in 2020.3.  Packager enforced in 2020.4.  Support removed in 2021.2.
=> Document support removal non-declarative attribute matching and normalizing

docs/design.md, docs/dialect.md
- restructure the Set connector capabilities section with sub-headings
- add the relevant capability names
- add MySQL8Dialect as a supported base dialect
- fix broken link on dialect page
=> document sub-queries and/or temp table support required

validation/tdr_latest.xsd
- Remove `Double-ST
- Remove `Float-ST`
- Remove `XML-RealSpecial-ST`
from tdr_latest.xsd
These are not used anywhere in the XSD and are not present in the [monolith](https://sourcegraph.prod.tableautools.com/teams/near/-/blob/modules/XSD/ConnectionResolverDefinition-root.xsd#L95).
=> Story 1272586: [SDK] Clean up tdr_latest.xsd

docs/dialect.md, docs/package-sign.md
This was causing copy-paste on some of the command code samples to not work correctly. 
Replace [NBSP](https://en.wikipedia.org/wiki/Non-breaking_space) with [space](https://en.wikipedia.org/wiki/Space_(punctuation)).
=> Replace non-breaking space with regular space

CHANGELOG.md, README.md
The changelog seems to have gotten a duplicated entry for adding the OAuth sample, which happened in master already. I also fixed the date for the last change added. We haven't been properly updating the changelog, that's something we should remember to do going forward.
=> Update readme and fix changelog for 2021.2

connector-packager/connector_packager/connector_properties.py, connector-packager/connector_packager/jar_jdk_packager.py, connector-packager/connector_packager/package.py, connector-packager/connector_packager/xml_parser.py, connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_connector_properties.py, connector-packager/tests/test_jar_packager.py, connector-packager/tests/test_resources/inferred_connection_resolver/connectionBuilder.js, connector-packager/tests/test_resources/inferred_connection_resolver/connectionFields.xml, connector-packager/tests/test_resources/inferred_connection_resolver/connectionMetadata.xml, connector-packager/tests/test_resources/inferred_connection_resolver/connectionProperties.js, connector-packager/tests/test_resources/inferred_connection_resolver/connectionResolver.xml, connector-packager/tests/test_resources/inferred_connection_resolver/dialect.xml, connector-packager/tests/test_resources/inferred_connection_resolver/manifest.xml, connector-packager/tests/test_resources/valid_connector/connection-dialog.tcd, connector-packager/tests/test_resources/valid_connector/manifest.xml, connector-packager/tests/test_xml_parser.py, connector-packager/tests/test_xsd_validator.py
- Sets min_tableau_version to 2021.1 if inferred connection resolver is used
- If no connection-normalizer element and connector uses Connection Dialog V1 (with a .tcd file), reject the connector
- Adds "ConnectorProperties", a new object that holds connector-wide properties that are derived from one file but needed by another file when validating the xml. (Needed to save the uses_tcd bool somewhere)
- Refactors parse_file so we only need to call validate_single_file on a file once for a given connector. Before, we'd run it twice: once to make sure that the xml file won't throw an error in parse_file, and once when running validate_all_xml
- Fixes the valid_connector test resource to use the strings from the resource file so we actually pick up the resource file in the file list
- Adds …
=> Enforce connection-normalizer rules in packager

connector-packager/connector_packager/connector_properties.py, connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_connector_properties.py, connector-packager/tests/test_resources/mcd_field_not_in_normalizer/connectionBuilder.js, connector-packager/tests/test_resources/mcd_field_not_in_normalizer/connectionFields.xml, connector-packager/tests/test_resources/mcd_field_not_in_normalizer/connectionMetadata.xml, connector-packager/tests/test_resources/mcd_field_not_in_normalizer/connectionProperties.js, connector-packager/tests/test_resources/mcd_field_not_in_normalizer/connectionResolver.xml, connector-packager/tests/test_resources/mcd_field_not_in_normalizer/dialect.xml, connector-packager/tests/test_resources/mcd_field_not_in_normalizer/manifest.xml, connector-packager/tests/test_xsd_validator.py
- Adds a new ConnectorProperty: connection_fields, which stores the connection fields
- Checks that all fields are in the required attributes list, rejects connector if one is missing
- Adds unit tests for the above scenario
=> Packager validates that all fields are in normalizer

samples/components/dialects/Hive12Dialect.tdd, validation/tdd_latest.xsd
Remove base dialect from Hive12dialect sample, made some changes based on recent DataDrivenDialect changes and what I found in TDVT test result(compared with builtin hive12dialect), there is one more issue that needs to be addressed regarding formatOrderBy, created [tfs 1297220 ](https://tfs.tsi.lan/tfs/DefaultCollection/Tableau-Dev/_workitems/edit/1297220/)
=> Remove base from hive12dialect sample

CHANGELOG.md, connector-packager/connector_packager/xml_parser.py, connector-packager/tests/test_resources/valid_connector/connection-dialog.tcd, connector-packager/tests/test_resources/valid_connector/manifest.xml
Manual test:
- Confirmed that the resources-fr_CA.xml file can be successfully packaged into a taco file 
- Ran the connector packaged with a resources-fr_CA.xml file and confirmed that the strings are correctly translated after setting the language to French (Canada) in Tableau.
Unit test:
- Added Story 1305320: [Connector SDK] Add unit test to test that resource files are correctly detected
Filed a bug found from testing:
- Defect 1306176: [Connector SDK] Connector without a resources-en_US.xml file for localized strings packages successfully and causes Tableau Desktop to hang on startup
Updating related SDK doc:
- PR - https://github.com/tableau/connector-plugin-sdk/pull/842
=> Add French (Canada) to supported languages

CHANGELOG.md, connector-packager/tests/test_resources/company_name_length_validation/max/manifest.xml, connector-packager/tests/test_resources/company_name_length_validation/min/manifest.xml, connector-packager/tests/test_xsd_validator.py, validation/connector_plugin_manifest_latest.xsd
Changes:
- Added max length constraint to company name (defined [here](https://sourcegraph.prod.tableautools.com/teams/near/-/blob/modules/connectors/tabconnectorsbase/public/infrastructure/IConnectorPlugin.h#L7:22); already [enforced](https://sourcegraph.prod.tableautools.com/teams/near/-/blob/modules/connectors/tabmixins/main/infrastructure/ConnectorPluginValidator.cpp#L62) at load time so this change shouldn't break any existing gallery connectors)
- Renamed type `NonEmptyString-ST` to `NonEmptyCompanyName-ST`. It was provided a generic name, however it now has constraint specifically applies to company name so renamed it (currently this type is only used to validate company name).
Testing:
- Change the company name in \samples\plugins\postgres_jdbc\manifest.xml to an empty string and …
=> Validate max length of company name

connector-packager/connector_packager/connector_properties.py, connector-packager/connector_packager/package.py, connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_connector_properties.py, connector-packager/tests/test_resources/advanced_required_missing_default/connectionFields.xml, connector-packager/tests/test_resources/authentication_attribute/connection_fields_no_authentication.xml, connector-packager/tests/test_resources/authentication_attribute/connection_fields_with_authentication.xml, connector-packager/tests/test_resources/duplicate_fields/connectionFields.xml, connector-packager/tests/test_resources/field_name_validation/invalid/ending_space/connectionFields.xml, connector-packager/tests/test_resources/field_name_validation/invalid/space_in_between/connectionFields.xml, connector-packager/tests/test_resources/field_name_validation/invalid/special_character/connectionFields.xml, connector-packager/tests/test_resources/field_name_validation/invalid/starting_number/connectionFields.xml, connector-packager/tests/test_resources/field_name_validation/invalid/starting_space/connectionFields.xml, connector-packager/tests/test_resources/field_name_validation/valid/connectionFields.xml, connector-packager/tests/test_resources/inferred_connection_resolver/connectionFields.xml, connector-packager/tests/test_resources/mcd_field_not_in_normalizer/connectionFields.xml, connector-packager/tests/test_resources/modular_dialog_connector/connectionFields.xml, connector-packager/tests/test_xsd_validator.py
Even if there is only one auth mode, we need to have the non-editable field in connection-fields so the default is properly set. Had to update a bunch of test files as well. (Plus, a bunch of whitespace changes since my VSCode is set to trim trailing spaces on saving.)
Also, right now authentication being missing in the connection-normalizer required attributes list is a warning, not an error. Is there a valid case for authentication not being there? I'm wondering if we should make that an error, or if I'm going about this PR wrong and should only warn if authentication is missing from the connection fields.
=> Validate that authentication field exists

connector-packager/connector_packager/connector_properties.py, connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_connector_properties.py, connector-packager/tests/test_resources/properties_builder/jdbc/connectionResolver.xml, connector-packager/tests/test_resources/properties_builder/odbc/connectionResolver.xml, connector-packager/tests/test_xsd_validator.py
Have the packager check for best practices from the samples and documentation.
Superclasses other than 'jdbc' can also be JDBC based, so make sure <connection-properties> validation is triggered on 'jdbc' or not 'jdbc'
=> Verify JDBC-based connectors use <connection-properties>

connector-packager/connector_packager/connector_properties.py, connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_connector_properties.py, connector-packager/tests/test_resources/database_field_not_in_normalizer/connectionBuilder.js, connector-packager/tests/test_resources/database_field_not_in_normalizer/connectionFields.xml, connector-packager/tests/test_resources/database_field_not_in_normalizer/connectionMetadata.xml, connector-packager/tests/test_resources/database_field_not_in_normalizer/connectionProperties.js, connector-packager/tests/test_resources/database_field_not_in_normalizer/connectionResolver.xml, connector-packager/tests/test_resources/database_field_not_in_normalizer/dialect.xml, connector-packager/tests/test_resources/database_field_not_in_normalizer/manifest.xml, connector-packager/tests/test_xsd_validator.py
When [database](https://tableau.github.io/connector-plugin-sdk/docs/mcd#the-connection-metadata-file) in connection-metadata.xml is enabled 'dbname' should be found in the `<required-attributes>` list.
The connection-metadata file and database element are both optional, enabled by default.
=> Enforce 'dbname' is present in required attributes if using "database" in connection-metadata

docs/metadata-enumeration.md
- clarify Database and Catalog terminology
- emphasis `dbname`, connection-metadata `database` and connection string requirement
- link to product documentation for cross-database join scenario
=> Catalog Hierarchy documentation

docs/mcd.md, docs/ui.md
Working on a packager warning as well. Makes it clear that vendor defined attributes will be logged, and that any field not marked secure will be logged.
=> Document non-secure attributes

_includes/docs_menu.html, docs/auth-modes.md, docs/connection-dialog.md, docs/mcd.md, docs/ui.md
- V1 and V2 details on their own pages
- Update auth-modes to be common guidance for both V1 and V2
- Move V1 specific content from auth-modes to ui.md
- Update left side navigation bar
=> Introduce common connection dialog page

connector-packager/connector_packager/connector_properties.py, connector-packager/connector_packager/package.py, connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_connector_properties.py, connector-packager/tests/test_resources/mcd_no_vendor_defined_fields/connectionFields.xml, connector-packager/tests/test_resources/mcd_no_vendor_defined_fields/connectionMetadata.xml, connector-packager/tests/test_resources/mcd_no_vendor_defined_fields/manifest.xml, connector-packager/tests/test_resources/tcd_vendor_defined_fields/connection-dialog.tcd, connector-packager/tests/test_resources/tcd_vendor_defined_fields/manifest.xml
- Detects vendor-defined fields from connection-fields and .tcd files and adds them to ConnectorProperties.vendor_defined_fields
- Displays all fields and tells user to confirm the inputs do not contain PII before distributing connector
- Adds tests for the new vendor_defined_fields
```
Detected vendor-defined fields:
['v-custom', 'v-custom2', 'vendor1', 'vendor2', 'vendor3']
Vendor-defined fields will be logged and persisted to Tableau workbook xml in plain text. You must confirm that the user inputs for fields listed above do not contain PII before distributing this connector to customers.
```
=> Packager displays vendor-defined fields and warns that they will be logged

docs/manual-test.md
We have had several partners fail this test, and they consistently mark it as passed, even when the error message is not correct. Trying to make it a lot more clear that they need to match the error message, not just have an error message thrown, and tell them what to do to fix it.
=> Revise invalid credentials test for clarity

samples/components/dialects/SQLDialect.tdd
Two functions identified that are defined by default
- TIME1899
-  SYS_NUMBIN ([tests](https://github.com/tableau/connector-plugin-sdk/search?q=SYS_NUMBIN&type=code))
=> Document default 'system' group functions

docs/mcd.md
The MCD list of supported auth modes was missing `auth-integrated`. Instead of keeping two lists in sync, just linking the MCD page to the authentication page.
=> Link MCD docs to authentication page

connector-packager/connector_packager/package.py
This is a brute-force way to allow some tacos that fail the packager's validation step to still be packaged. For example, the recent Dremio issue where the validation rules were wrong and forced them to incorrectly add required attributes. 
Tested with the Dremio scenario, and it would have worked for them. For connectors with actual XML issues, the file list is not generated so if --force-package is used the packager will crash with a python error. This is fine in my opinion, those connectors would not load in Tableau anyway, we give plenty of warning, and we're not looking to document this outside of the built-in help for the packager.
=> Add force-package argument

docs/manual-test.md
First attempt at making manual test passes less onerous for partners.
Removed:
- "Verify that you can duplicate the data source" step
- `Verify that the data source connection properties are correct.`
- "Edit your connection" step - they may not have multiple endpoints to test against.
- "Missing connector" steps
Added:
- connecting with each supported auth mode
=> Update manual test plan for partners

_includes/docs_menu.html, docs/connection-dialog.md, docs/design.md, docs/gallery-submission.md, docs/security-considerations.md
First stab at adding the Security Considerations page. We want to document the common security reasons we reject connectors from the Exchange.
=> Add security considerations page

docs/oauth.md
During review with Plantair, they found we are lacking the information tha id-token needs to be in the accessTokenResponseMap to be able to return username. Adding that.
=> Add id-token information.

docs/gallery-submission.md
Noted that the Tableau Exchange accepts only JDBC connectors now.
=> Add JDBC-only requirement to submission guidelines

docs/run-taco.md, docs/templates/tableau-server.md
The "Run Your Connector" page did not have the Prep instructions, and the templates did not have the directory for general Tableau, just Prep. (My fault, based on my review feedback.) Adding them both, and trying to unify the formatting a bit.
=> Fix incomplete Tableau server instructions

docs/run-taco.md, docs/templates/tableau-server.md
- Document Shared Taco directory as an option for Server. Label it as our preferred option.
- Properly document minerva directory for old way of installing on Server
- Update the installation templates for Server.
=> Document shared taco directory

docs/run-taco.md
Documents that we load newer versions of connectors when there is a class name collision in 2022.2
=> Document versioning change in 2022.2

docs/gallery-submission.md
Revised how to submit a connector based on:
- The new Contributor Console on the Exchange website
- The process for using GitHub to collect review materials (tfs [1373838](https://tfs.tsi.lan/tfs/DefaultCollection/Tableau-Dev/_workitems/edit/1373838))
- Input from the Partner Network about joining the program and go-to-market materials
=> Updating submission process for connectors 

connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_resources/server_attribute/connection_fields_with_no_server.xml, connector-packager/tests/test_resources/server_attribute/connection_fields_with_server.xml, connector-packager/tests/test_resources/server_attribute/no_required_attributes_list.tdr, connector-packager/tests/test_resources/server_attribute/with_server.tdr, connector-packager/tests/test_resources/server_attribute/without_server.tdr, connector-packager/tests/test_xsd_validator.py
[SDK] Packager to enforce 'server' as a required attribute
- Added the packager to warn users when 'server' is not present in the attribute list 
- Added tests to check this the code functions as intended.
=> Story 1324999: Warn users when server is not present as required attribute

docs/security-considerations.md
- Internal links had extra pair of parentheses
- Fix link to Tableau help page
=> Fix broken links

docs/design.md
Justin pointed out that we said min-tableau-version instead of min-version-tableau in the docs, fixed that typo. Also took the opportunity to update the blurb based on new packager functionality since the original doc was written.
=> Fix typo, update min-version-tableau docs

docs/api-reference.md, docs/auth-modes.md, docs/capabilities.md, docs/connection-dialog.md, docs/design.md, docs/dialect.md, docs/drivers.md, docs/example.md, docs/index.md, docs/localize.md, docs/log-entries.md, docs/manual-test.md, docs/mcd.md, docs/metadata-enumeration.md, docs/oauth.md, docs/package-sign.md, docs/run-taco.md, docs/security-considerations.md, docs/tdvt-test-case.md, docs/tdvt.md, docs/ui.md
Adds table of contents to all relevant doc pages as a quick hackathon thing, using the format first used on this page: https://tableau.github.io/connector-plugin-sdk/docs/gallery-submission. Automatically generates the table of contents based on the headers in markdown, although markdown previews don't appear to work. 
This makes it easier to jump to a certain section, and makes it easier for us to send a direct link to a certain section when providing feedback during reviews.
Tested locally and confirmed the pages appear correct. 
Also, have VS Code set to automatically delete trailing whitespace when I save. Because I touched every page, the diffs also have a bunch of whitespace getting removed.
=> Add table of contents to doc pages

validation/tdd_latest.xsd
- 'DBDATE' value was missing as a valid value in RemoteType-ST
- 'DATE' value was listed twice in RemoteType-ST
- update second 'DATE' to 'DBDATE' to allow support for DBTYPE_DBDATE
=> Update dialect XSD to include 'DBDATE' in RemoteType-ST

docs/capabilities.md
Previously documented default value was incorrect. No changes have occurred in the platform.
=> Update CAP_SUPPORTS_UNION documentation

samples/components/dialects/FullFunctionMap.tdd
The `<function>` definitions for `name='MAX'` and `name='MIN'` in `group='numeric'` should contain either `return-type='real'` or `return-type='int'`.
=> remove duplicate and incorrect MIN/MAX definitions

tdvt/tdvt/tabquery.py, tdvt/test/tdvt_test.py
Change for internal consumption. Removes unit test for logic, too.
=> Remove TabExtension logic to fix perf logging

docs/tdvt.md
Note from @lukewrites:
Docs listed incorrect exclusions name and test case name. Apparently no one had tried excluding this test before because when we excluded the test case we found a TDVT bug
=> W-12616204 Update TDVT documentation around LODTests

CHANGELOG.md, connector-packager/connector_packager/jar_jdk_packager.py, connector-packager/tests/test_jar_packager.py, connector-packager/tests/test_resources/oauth_connector/oauth-config-with-suffix.xml, connector-packager/tests/test_resources/oauth_instance_url_suffix/invalid/oauth-config.xml, connector-packager/tests/test_resources/oauth_instance_url_suffix/valid/oauth-config.xml, connector-packager/tests/test_xsd_validator.py, validation/oauth_config.xsd
Add support for `instanceUrlSuffix` in the Connector Plugin SDK.  I am starting this in 2023.2 as it is currently supported in this release, however, we are currently in the process of backporting the support of this to 2023.1 as well.  Once the monolith changes have been backported to 2023.1, I will also backport these changes in the SDK branch to master/dev-2023.1.
=> @W-12594606: [OAuth][SDK] Add `instanceUrlSuffix` field to Connector SDK

docs/oauth.md
Add support for instanceUrlSuffix in the Connector Plugin SDK. I am starting this in 2023.2 as it is currently supported in this release, however, we are currently in the process of backporting the support of this to 2023.1 as well. Once the monolith changes have been backported to 2023.1, I will also backport these changes in the SDK branch to master/dev-2023.1.
=> @W-12594606: [OAuth][SDK] Add instanceUrlSuffix field to Connector SDK

CHANGELOG.md, connector-packager/connector_packager/jar_jdk_packager.py, connector-packager/tests/test_jar_packager.py, connector-packager/tests/test_resources/oauth_config_label/invalid/oauth-config.xml, connector-packager/tests/test_resources/oauth_config_label/valid/oauth-config.xml, connector-packager/tests/test_resources/oauth_connector/oauth-config-with-label.xml, connector-packager/tests/test_xsd_validator.py, validation/oauth_config.xsd
Add support for `configLabel` in the Connector Plugin SDK. 
The monolith changes were added in 2023.2 so this is only supported in 2023.2 and beyond.
=> @W-12971224: [OAuth][SDK] Add `configLabel` field to Connector SDK

CHANGELOG.md, connector-packager/connector_packager/jar_jdk_packager.py, connector-packager/tests/test_jar_packager.py, connector-packager/tests/test_resources/oauth_connector/oauth-config-with-default-instance-url.xml, connector-packager/tests/test_resources/oauth_default_instance_url/invalid/oauth-config.xml, connector-packager/tests/test_resources/oauth_default_instance_url/valid/oauth-config.xml, connector-packager/tests/test_xsd_validator.py, validation/oauth_config.xsd
Adds support for defaultInstanceUrl and sets minimum version to 2023.3 when present.
As we don't know what the versioning system looks like for tableau in the future, this might have to be changed to 246 or whatever is chosen...
=> @W-12314727 - [OAuth-Service][Plugins] Default Instance URL support for SDK

docs/oauth.md
Depending on the underlying OAuth provider being used `clientSecretDesktop` can be either required or optional. Change the documentation to 'Recommended' to better clarify this might be required.
=> Update clientSecretDesktop to be 'Recommended'

tdvt/tdvt/tdvt_core.py
Currently the generated test_results_combined.csv is missing values in the "Actual (100)tuples" and "Expected (100)tuples" columns.
There is a bug in [`get_csv_header_data`](https://github.com/tableau/connector-plugin-sdk/blob/b2db407e52309d9a7f50d81e738fa9554e7d9c8c/tdvt/tdvt/tdvt_core.py#L642). If we call this function multiple times, the returned string list changes: we continuously extend `[actual_tuples_header, actual_tuples_header]` to the list. This is because [here](https://github.com/tableau/connector-plugin-sdk/blob/b2db407e52309d9a7f50d81e738fa9554e7d9c8c/tdvt/tdvt/tdvt_core.py#L651) is not a value copy but a reference assignment.
If the csv file's header has duplicate column names, the csv.DictReader [parses](https://github.com/tableau/connector-plugin-sdk/blob/b2db407e52309d9a …
=> Fix a bug that the actual and expected values are missing in test_results_combined.csv.

docs/package-sign.md
Aligning with the internal doc that timestamp is required when signing taco.
=> @W-13285596: [SDK] Update doc to reflect that timestamp is required

docs/oauth-dev.md, docs/oauth.md
I split this up because I will have the general OAuth instructions linked to from the main Tableau docs for the admins to setup custom OAuth config. The admins shouldn’t need to know about plugin things like javascript and manifests, etc.
Also do some cleanup
- Remove references to "external" config to simplify things. We will just call that "custom."
- Other rewording.
- Changed the main example to use fixed IDP URLs since the custom domain is only for embedded, which is only available for devs.
I validated that all the links work. Some redirect to the section in the other page now.
=> Split OAuth docs into dev and general

connector-packager/connector_packager/jar_jdk_packager.py, connector-packager/connector_packager/xml_parser.py, connector-packager/tests/test_jar_packager.py, connector-packager/tests/test_resources/null_oauth_config/connectionBuilder.js, connector-packager/tests/test_resources/null_oauth_config/connectionFields.xml, connector-packager/tests/test_resources/null_oauth_config/connectionResolver.xml, connector-packager/tests/test_resources/null_oauth_config/dialect.xml, connector-packager/tests/test_resources/null_oauth_config/manifest.xml
- Tacos with null OAuth config are packaged
- min_tableau_version set to 2024.1 (can always update if we backport)
- Adds a new test, confirmed all other tests pass
Opening new pull request to try and get the cla bot to work. Sorry for the spam.
Old PR: https://github.com/tableau/connector-plugin-sdk/pull/1170
=> Add support for null oauth config in packager

docs/index.md, docs/package-sign.md, docs/tdvt.md
Update install instructions to only use `pip` rather than calling `setup.py`.  Removes some instructions that shouldn't matter to end users, and also removes the `python pip` calls with plain `pip` calls.
This should close #1203. 
Related: #1216
=> remove setup.py references

samples/components/oauth/athena.okta.xml, samples/components/oauth/redshift.azure.iam-idc.xml, samples/components/oauth/redshift.azure.xml
Update OAuth examples
- Add example for Azure with IAM IDC which requires a custom scope
- Add more comments
- Switch username mapping to use email
- Add an example with a config label
- Remove invalid response parameter from Azure (access-token-issue-time)
=> Update OAuth examples

docs/package-sign.md
Seems many certificate authorities now require HSM to generate certificate requests. Adding some notes about that, and emphasizing that our docs for signing are provided as an example, and to check the documentation for the certificate authority for additional requirements. We don't go through the signing process enough to keep up with industry changes.
=> Add note about HSMs

docs/oauth-dev.md
Change is already in, and the packager already handles this case. Once this is merged we can close https://github.com/tableau/connector-plugin-sdk/issues/1108
=> Add null oauth docs

connector-packager/connector_packager/jar_jdk_packager.py, connector-packager/tests/test_jar_packager.py
I double checked, and turns out we backported this fix to 2023.3, but the packager stamps the minimum version as 2024.1. Corrected this mistake on the issue and now fixing the packager.
=> Fix null oauth version check

connector-packager/connector_packager/xml_parser.py
Add dutch language to the package so that it is accepted for partner connectors. 
All the connectors already have updated dutch language support in https://sourcegraph.prod.tableautools.com/github.com/sf-analyticscloud/monolith/-/tree/modules/connectors/connector_plugins/plugins
=> @W-16327429: Enable a new language Dutch for all connectors

samples/components/oauth/saphana.okta.xml, samples/components/oauth/snowflake.azure.xml
=> add sample for hana external oauth

_includes/footer.html, _includes/head.html, css/main.css
=====
Checking in update to the documentation (`gh-pages`) branch. Added cookie manager and related OneTrust code. This is so we can start collecting Google Analytics (GA4)  data (page views) again.
=> @gus W-17274770 Added cookie manager and links to footer

docs/capabilities.md
Added documentation for CAP_ODBC_INCLUDE_CATALOG_NAME and CAP_JDBC_SUPPRESS_CATALOG_NAME.  Verified documentation from the preview of the capabilities.md file and found content is loading properly.
=====
=> @W-17779296 - Update SDK docs for CAP_XDBC_INCLUDE_CATALOG_NAME

docs/oauth.md
- Add more information on desktop client secret.
- Update main example, the full auth/token URIs are incompatible with custom domain. The code will append those to the custom domain.
- Add another example with the full URLs.
=> OAuth Doc Updates 07/25

connector-packager/CHANGELOG.md, connector-packager/connector_packager/xsd_validator.py, connector-packager/tests/test_resources/field_name_validation/invalid/non_password_secure_field/connectionFields.xml, connector-packager/tests/test_resources/field_name_validation/invalid/prohibited_word/connectionFields.xml, connector-packager/tests/test_resources/field_name_validation/invalid/prohibited_word_label/connectionFields.xml, connector-packager/tests/test_xsd_validator.py
Makes two changes:
- If the field is marked secure, and the field name is not `password`, fail packager validation. These connectors will not work in Tableau.
- If the field has token, password, or secret in it, and is not marked secure, fail the validation, since that suggests that field would leak customer secrets. Open to making this a non-failing warning, but given we already have a warning I'd kind of rather err on the side of caution
Also adds two new test cases to cover these scenarios.
For work item W-19338086
=> Check for prohibited words in non-secure field
